spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
logging.pattern.console=%-4relative [%thread] %-5level %logger{35} %X{CorrelationId} --- %msg %n
spring.messages.basename=messages

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

project.datasource.engine=MYSQL
project.datasource.host-name=mysql-server

jwt.secret=304f42d8711889585a433a9ec28ebae231a3c379c61b6199023b6ae00a6d4a3d
# Token expiration time in milliseconds (e.g., 24 hours)
jwt.expiration=86400000